export const dataEntity = 'SC'

export const vtexAppKey = 'vtexappkey-colgatedireto-AEABJL'
export const vtexAppToken =
  'NPTATRSOMARZJNJEPFRXRVTBSYTJXHIOENMYTCHEETJKKTGHTITBQAQRWSIVYJRESCUVALKNXMSYMIQZSMPOOHYEXVCBUMFVCESIZLGIXFDDHSFNCJCMTCQLEQXFIJTK'
